# Generated by Django 3.2 on 2021-05-07 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatmessage',
            name='messageUsername',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messageUsername', to='auth.user'),
            preserve_default=False,
        ),
    ]
