# Generated by Django 3.2 on 2021-05-07 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_auto_20210507_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='users',
        ),
        migrations.AddField(
            model_name='groupchat',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
