# Generated by Django 3.2 on 2021-05-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210507_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupList',
        ),
    ]
