# Generated by Django 3.2 on 2021-05-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_delete_grouplist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar.png', max_length=200, upload_to='userprofile/'),
        ),
    ]
