# Generated by Django 3.2 on 2021-05-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='image',
            field=models.ImageField(default='userprofile/gp.png', upload_to='userprofile/'),
        ),
    ]
